// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyAbe3ub9mdvY2g0efFlkWuoaEeBxz2Mg',
    appId: '1:497631097507:web:bc5ccf91b8576607de4516',
    messagingSenderId: '497631097507',
    projectId: 'login-form-c3928',
    authDomain: 'login-form-c3928.firebaseapp.com',
    storageBucket: 'login-form-c3928.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRmmxW5c8qraqQ9Z_8Pu91C_BJDlcitJc',
    appId: '1:497631097507:android:897438385778324fde4516',
    messagingSenderId: '497631097507',
    projectId: 'login-form-c3928',
    storageBucket: 'login-form-c3928.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAL0_Fx1RXznALyzyHzkRGwOT49doB2EKU',
    appId: '1:497631097507:ios:9e669083cea9c48dde4516',
    messagingSenderId: '497631097507',
    projectId: 'login-form-c3928',
    storageBucket: 'login-form-c3928.appspot.com',
    iosBundleId: 'com.example.testing',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAL0_Fx1RXznALyzyHzkRGwOT49doB2EKU',
    appId: '1:497631097507:ios:9e669083cea9c48dde4516',
    messagingSenderId: '497631097507',
    projectId: 'login-form-c3928',
    storageBucket: 'login-form-c3928.appspot.com',
    iosBundleId: 'com.example.testing',
  );
}
